<?php

namespace Smartprax\Medidoc\Entities;

class PatientFullData
{
    public function __construct(
        public int $ReturnValue,
        public \DateTimeInterface $ValidFromdate,
        public \DateTimeInterface $ValidTodate,
        public string $InsuranceGLN,
        public string $InsuranceBAGID,
        public string $InsuranceName,
        public string $CardID,
        public string $AssuredID,
        public string $AHV,
        public string $Language,
        public string $Firstname,
        public string $Lastname,
        public \DateTimeInterface $Birthdate,
        public string $Gender,
        public string $Street,
        public string $Pobox,
        public string $Zip,
        public string $City,
        public string $Country,
        public string $Kvg,
        public string $KvgModel,
        public string $KvgRegion,
        public string $KvgAccident,
        public bool $KvgAssuredDataLocked,
        public bool $KvgBenefitDelay,
        public string $KvgProduct1,
        public string $KvgProduct2,
        public string $KvgProduct3,
        public string $DrugsHorsList,
        public string $DrugsHorsListAccident,
        public string $DrugsComplementary,
        public string $DrugsComplementaryAccident,
        public bool $DrugsBenefitDelay,
        public string $HospitalUnit,
        public string $HospitalModel,
        public string $HospitalAccident,
        public string $HospitalAkutSomatik,
        public string $HospitalPsychiatry,
        public string $HospitalList,
        public bool $HospitalBenefitDelay,
        public string $VvgProduct1,
        public string $VvgProduct2,
        public string $VvgProduct3,
        public string $VvgProduct4,
        public string $VvgProduct5,
        public string $VvgProduct6,
        public string $VvgProduct7,
        public string $VvgProduct8,
    )
    {}
}
