<?php

namespace Smartprax\Medidoc;

use Smartprax\Medidoc\Entities;
use Soap\ExtSoapEngine\Configuration\ClassMap\ClassMap;
use Soap\ExtSoapEngine\Configuration\ClassMap\ClassMapCollection;

class MedidocClassmap
{
    public static function getCollection(): ClassMapCollection
    {
        return new ClassMapCollection(
            new ClassMap('CheckConnection', Entities\CheckConnection::class),
            new ClassMap('CheckConnectionResponse', Entities\CheckConnectionResponse::class),
            new ClassMap('SendDocument', Entities\SendDocument::class),
            new ClassMap('DocumentData', Entities\DocumentData::class),
            new ClassMap('PatientData', Entities\PatientData::class),
            new ClassMap('ArrayOfNameValue', Entities\ArrayOfNameValue::class),
            new ClassMap('NameValue', Entities\NameValue::class),
            new ClassMap('SendDocumentResponse', Entities\SendDocumentResponse::class),
            new ClassMap('SendDocumentList', Entities\SendDocumentList::class),
            new ClassMap('ArrayOfDocumentData', Entities\ArrayOfDocumentData::class),
            new ClassMap('SendDocumentListResponse', Entities\SendDocumentListResponse::class),
            new ClassMap('ArrayOfSendDocumentResponse', Entities\ArrayOfSendDocumentResponse::class),
            new ClassMap('GetDocumentStates', Entities\GetDocumentStates::class),
            new ClassMap('GetDocumentStatesResponse', Entities\GetDocumentStatesResponse::class),
            new ClassMap('DocumentStatesResponse', Entities\DocumentStatesResponse::class),
            new ClassMap('ArrayOfDocumentStatus', Entities\ArrayOfDocumentStatus::class),
            new ClassMap('DocumentStatus', Entities\DocumentStatus::class),
            new ClassMap('GetDocumentStatesByDocumentID', Entities\GetDocumentStatesByDocumentID::class),
            new ClassMap('GetDocumentStatesByDocumentIDResponse', Entities\GetDocumentStatesByDocumentIDResponse::class),
            new ClassMap('GetDocumentStatesHistory', Entities\GetDocumentStatesHistory::class),
            new ClassMap('GetDocumentStatesHistoryResponse', Entities\GetDocumentStatesHistoryResponse::class),
            new ClassMap('GetDocumentStatesHistoryByDocumentID', Entities\GetDocumentStatesHistoryByDocumentID::class),
            new ClassMap('GetDocumentStatesHistoryByDocumentIDResponse', Entities\GetDocumentStatesHistoryByDocumentIDResponse::class),
            new ClassMap('GetPendingDocumentsStatesList', Entities\GetPendingDocumentsStatesList::class),
            new ClassMap('GetPendingDocumentsStatesListResponse', Entities\GetPendingDocumentsStatesListResponse::class),
            new ClassMap('PendingDocumentsStatesResponse', Entities\PendingDocumentsStatesResponse::class),
            new ClassMap('ArrayOfDocumentStatesResponse', Entities\ArrayOfDocumentStatesResponse::class),
            new ClassMap('SendDocumentStatesAcknowledgement', Entities\SendDocumentStatesAcknowledgement::class),
            new ClassMap('SendDocumentStatesAcknowledgementResponse', Entities\SendDocumentStatesAcknowledgementResponse::class),
            new ClassMap('GenericResponse', Entities\GenericResponse::class),
            new ClassMap('GetFolderContentList', Entities\GetFolderContentList::class),
            new ClassMap('GetFolderContentListResponse', Entities\GetFolderContentListResponse::class),
            new ClassMap('FolderContentResponse', Entities\FolderContentResponse::class),
            new ClassMap('ArrayOfGuid', Entities\ArrayOfGuid::class),
            new ClassMap('GetDocumentContent', Entities\GetDocumentContent::class),
            new ClassMap('GetDocumentContentResponse', Entities\GetDocumentContentResponse::class),
            new ClassMap('ContentResponse', Entities\ContentResponse::class),
            new ClassMap('GetDocumentContentByDocumentID', Entities\GetDocumentContentByDocumentID::class),
            new ClassMap('GetDocumentContentByDocumentIDResponse', Entities\GetDocumentContentByDocumentIDResponse::class),
            new ClassMap('GetDocumentResponseContent', Entities\GetDocumentResponseContent::class),
            new ClassMap('GetDocumentResponseContentResponse', Entities\GetDocumentResponseContentResponse::class),
            new ClassMap('GetDocumentResponseContentByDocumentID', Entities\GetDocumentResponseContentByDocumentID::class),
            new ClassMap('GetDocumentResponseContentByDocumentIDResponse', Entities\GetDocumentResponseContentByDocumentIDResponse::class),
            new ClassMap('CancelDocument', Entities\CancelDocument::class),
            new ClassMap('CancelDocumentResponse', Entities\CancelDocumentResponse::class),
            new ClassMap('CancelDocumentByDocumentID', Entities\CancelDocumentByDocumentID::class),
            new ClassMap('CancelDocumentByDocumentIDResponse', Entities\CancelDocumentByDocumentIDResponse::class),
            new ClassMap('CompleteDocument', Entities\CompleteDocument::class),
            new ClassMap('CompleteDocumentResponse', Entities\CompleteDocumentResponse::class),
            new ClassMap('CompleteDocumentByDocumentID', Entities\CompleteDocumentByDocumentID::class),
            new ClassMap('CompleteDocumentByDocumentIDResponse', Entities\CompleteDocumentByDocumentIDResponse::class),
            new ClassMap('SendPartialPayment', Entities\SendPartialPayment::class),
            new ClassMap('SendPartialPaymentResponse', Entities\SendPartialPaymentResponse::class),
            new ClassMap('SendPartialPaymentByDocumentID', Entities\SendPartialPaymentByDocumentID::class),
            new ClassMap('SendPartialPaymentByDocumentIDResponse', Entities\SendPartialPaymentByDocumentIDResponse::class),
            new ClassMap('OrderPrintService', Entities\OrderPrintService::class),
            new ClassMap('Address', Entities\Address::class),
            new ClassMap('OrderPrintServiceResponse', Entities\OrderPrintServiceResponse::class),
            new ClassMap('OrderPrintServiceByDocumentID', Entities\OrderPrintServiceByDocumentID::class),
            new ClassMap('OrderPrintServiceByDocumentIDResponse', Entities\OrderPrintServiceByDocumentIDResponse::class),
            new ClassMap('GetNewInsuranceAddress', Entities\GetNewInsuranceAddress::class),
            new ClassMap('GetNewInsuranceAddressResponse', Entities\GetNewInsuranceAddressResponse::class),
            new ClassMap('AddressResponse', Entities\AddressResponse::class),
            new ClassMap('GetNewInsuranceAddressByDocumentID', Entities\GetNewInsuranceAddressByDocumentID::class),
            new ClassMap('GetNewInsuranceAddressByDocumentIDResponse', Entities\GetNewInsuranceAddressByDocumentIDResponse::class),
            new ClassMap('GetGlnPartyData', Entities\GetGlnPartyData::class),
            new ClassMap('GetGlnPartyDataResponse', Entities\GetGlnPartyDataResponse::class),
            new ClassMap('GlnPartyDataResponse', Entities\GlnPartyDataResponse::class),
            new ClassMap('ArrayOfGlnPartyData', Entities\ArrayOfGlnPartyData::class),
            new ClassMap('GlnPartyData', Entities\GlnPartyData::class),
            new ClassMap('SearchGlnPartyData', Entities\SearchGlnPartyData::class),
            new ClassMap('SearchGlnPartyDataResponse', Entities\SearchGlnPartyDataResponse::class),
            new ClassMap('GetInsuranceList', Requests\GetInsuranceList::class),
            //new ClassMap('GetInsuranceListResult', Responses\GetInsuranceListResult::class),
            new ClassMap('GetInsuranceListResult', Responses\GetInsuranceListResult::class),
            new ClassMap('ArrayOfInsuranceData', Entities\ArrayOfInsuranceData::class),
            new ClassMap('InsuranceData', Entities\InsuranceData::class),
            new ClassMap('GetPersonOrOrganizationList', Entities\GetPersonOrOrganizationList::class),
            new ClassMap('GetPersonOrOrganizationListResponse', Entities\GetPersonOrOrganizationListResponse::class),
            new ClassMap('PersonOrOrganizationListResponse', Entities\PersonOrOrganizationListResponse::class),
            new ClassMap('ArrayOfPersonOrOrganization', Entities\ArrayOfPersonOrOrganization::class),
            new ClassMap('PersonOrOrganization', Entities\PersonOrOrganization::class),
            new ClassMap('ArrayOfCodeValue', Entities\ArrayOfCodeValue::class),
            new ClassMap('CodeValue', Entities\CodeValue::class),
            new ClassMap('GetPatientDataByInsuranceCardNumber', Entities\GetPatientDataByInsuranceCardNumber::class),
            new ClassMap('GetPatientDataByInsuranceCardNumberResponse', Entities\GetPatientDataByInsuranceCardNumberResponse::class),
            new ClassMap('PatientFullData', Entities\PatientFullData::class),
            new ClassMap('GetPatientDataByPatientIdentityDetails', Entities\GetPatientDataByPatientIdentityDetails::class),
            new ClassMap('GetPatientDataByPatientIdentityDetailsResponse', Entities\GetPatientDataByPatientIdentityDetailsResponse::class),
            new ClassMap('GetPendingVesrRecords', Entities\GetPendingVesrRecords::class),
            new ClassMap('GetPendingVesrRecordsResponse', Entities\GetPendingVesrRecordsResponse::class),
            new ClassMap('VesrRecordsResponse', Entities\VesrRecordsResponse::class),
            new ClassMap('SendVesrRecordsAcknowledgement', Entities\SendVesrRecordsAcknowledgement::class),
            new ClassMap('SendVesrRecordsAcknowledgementResponse', Entities\SendVesrRecordsAcknowledgementResponse::class),
            new ClassMap('GetPendingCamt54File', Entities\GetPendingCamt54File::class),
            new ClassMap('GetPendingCamt54FileResponse', Entities\GetPendingCamt54FileResponse::class),
            new ClassMap('Camt54FileResponse', Entities\Camt54FileResponse::class),
            new ClassMap('ArrayOfString', Entities\ArrayOfString::class),
            new ClassMap('SendCamt54FilesAcknowledgement', Entities\SendCamt54FilesAcknowledgement::class),
            new ClassMap('SendCamt54FilesAcknowledgementResponse', Entities\SendCamt54FilesAcknowledgementResponse::class),
            new ClassMap('GetPendingReminders', Entities\GetPendingReminders::class),
            new ClassMap('GetPendingRemindersResponse', Entities\GetPendingRemindersResponse::class),
            new ClassMap('RemindersResponse', Entities\RemindersResponse::class),
            new ClassMap('ArrayOfReminderInfo', Entities\ArrayOfReminderInfo::class),
            new ClassMap('ReminderInfo', Entities\ReminderInfo::class),
            new ClassMap('SendReminderAcknowledgement', Entities\SendReminderAcknowledgement::class),
            new ClassMap('SendReminderAcknowledgementResponse', Entities\SendReminderAcknowledgementResponse::class),
            new ClassMap('GetPendingNotifications', Entities\GetPendingNotifications::class),
            new ClassMap('GetPendingNotificationsResponse', Entities\GetPendingNotificationsResponse::class),
            new ClassMap('NotificationsResponse', Entities\NotificationsResponse::class),
            new ClassMap('ArrayOfNotificationInfo', Entities\ArrayOfNotificationInfo::class),
            new ClassMap('NotificationInfo', Entities\NotificationInfo::class),
            new ClassMap('NotificationReferenceInfo', Entities\NotificationReferenceInfo::class),
            new ClassMap('SendNotificationAcknowledgement', Entities\SendNotificationAcknowledgement::class),
            new ClassMap('SendNotificationAcknowledgementResponse', Entities\SendNotificationAcknowledgementResponse::class),
            new ClassMap('ConvertXmlToPdf', Entities\ConvertXmlToPdf::class),
            new ClassMap('ConvertXmlToPdfResponse', Entities\ConvertXmlToPdfResponse::class),
            new ClassMap('GetProviderConfiguration', Entities\GetProviderConfiguration::class),
            new ClassMap('GetProviderConfigurationResponse', Entities\GetProviderConfigurationResponse::class),
            new ClassMap('ProviderConfigurationResponse', Entities\ProviderConfigurationResponse::class),
            new ClassMap('UploadEsrFile', Entities\UploadEsrFile::class),
            new ClassMap('UploadEsrFileResponse', Entities\UploadEsrFileResponse::class),
            new ClassMap('GetSuvaClaimStatusInfo', Entities\GetSuvaClaimStatusInfo::class),
            new ClassMap('GetSuvaClaimStatusInfoResponse', Entities\GetSuvaClaimStatusInfoResponse::class),
            new ClassMap('SuvaClaimStatusInfoResponse', Entities\SuvaClaimStatusInfoResponse::class),
            new ClassMap('GetSuvaInvoiceStatusInfo', Entities\GetSuvaInvoiceStatusInfo::class),
            new ClassMap('GetSuvaInvoiceStatusInfoResponse', Entities\GetSuvaInvoiceStatusInfoResponse::class),
            new ClassMap('SuvaInvoiceStatusInfoResponse', Entities\SuvaInvoiceStatusInfoResponse::class),
            new ClassMap('ArrayOfSuvaInvoiceStatusInfoResponseFurtherInformation', Entities\ArrayOfSuvaInvoiceStatusInfoResponseFurtherInformation::class),
            new ClassMap('SuvaInvoiceStatusInfoResponseFurtherInformation', Entities\SuvaInvoiceStatusInfoResponseFurtherInformation::class),
        );
    }
}
